ERROR - 2023-12-11 04:19:05 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:19:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l_name,address FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:19:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:19:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l_name  FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:19:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:19:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l_name  FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:19:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:19:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l_name  FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:20:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:20:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l_name  FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:21:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:21:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l_name  FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:21:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:21:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT f_name,l_name  FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:22:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:22:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:22:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:22:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:23:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:23:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:23:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:23:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-11 04:24:58 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'DBSymphony', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 C:\xampp\htdocs\codeigniter4\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter4\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\codeigniter4\system\Common.php(1190): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(10): view('welcome_message')
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(942): App\Controllers\Home->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-11 04:24:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM users')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(10): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:35:22 --> Undefined variable $results
in APPPATH\Views\welcome_message.php on line 14.
 1 APPPATH\Views\welcome_message.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $results', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php', 14)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(24): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:35:40 --> Undefined variable $results
in APPPATH\Views\welcome_message.php on line 14.
 1 APPPATH\Views\welcome_message.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $results', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php', 14)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(24): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:36:01 --> Undefined variable $results
in APPPATH\Views\welcome_message.php on line 14.
 1 APPPATH\Views\welcome_message.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $results', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php', 14)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(24): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:39:03 --> Undefined property: App\Controllers\Home::$load
in APPPATH\Controllers\Home.php on line 23.
 1 APPPATH\Controllers\Home.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Home::$load', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:42:00 --> Undefined property: App\Controllers\Home::$load
in APPPATH\Controllers\Home.php on line 23.
 1 APPPATH\Controllers\Home.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Home::$load', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:43:58 --> Undefined variable $results
in APPPATH\Views\welcome_message.php on line 14.
 1 APPPATH\Views\welcome_message.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $results', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php', 14)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(26): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:45:11 --> view(): Argument #2 ($data) must be of type array, string given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php on line 27
in SYSTEMPATH\Common.php on line 1178.
 1 APPPATH\Controllers\Home.php(27): view('welcome_message', 'ok')
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:45:13 --> view(): Argument #2 ($data) must be of type array, string given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php on line 27
in SYSTEMPATH\Common.php on line 1178.
 1 APPPATH\Controllers\Home.php(27): view('welcome_message', 'ok')
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:45:20 --> view(): Argument #2 ($data) must be of type array, string given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php on line 27
in SYSTEMPATH\Common.php on line 1178.
 1 APPPATH\Controllers\Home.php(27): view('welcome_message', 'ok')
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:45:40 --> view(): Argument #2 ($data) must be of type array, string given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php on line 27
in SYSTEMPATH\Common.php on line 1178.
 1 APPPATH\Controllers\Home.php(27): view('welcome_message', 'ok')
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 04:45:42 --> view(): Argument #2 ($data) must be of type array, string given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php on line 27
in SYSTEMPATH\Common.php on line 1178.
 1 APPPATH\Controllers\Home.php(27): view('welcome_message', 'ok')
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:36:04 --> Declaration of App\Models\Home\User::insert() must be compatible with CodeIgniter\Model::insert($data = null, bool $returnID = true)
in APPPATH\Models\Home\User.php on line 41.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-11 05:36:06 --> Declaration of App\Models\Home\User::insert() must be compatible with CodeIgniter\Model::insert($data = null, bool $returnID = true)
in APPPATH\Models\Home\User.php on line 41.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-11 05:36:33 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 28.
 1 APPPATH\Controllers\Home.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 28)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:36:56 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 28.
 1 APPPATH\Controllers\Home.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 28)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:38:10 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 28.
 1 APPPATH\Controllers\Home.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 28)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:39:03 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 28.
 1 APPPATH\Controllers\Home.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 28)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:40:07 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 27.
 1 APPPATH\Controllers\Home.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 27)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:40:09 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 27.
 1 APPPATH\Controllers\Home.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 27)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:40:25 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 27.
 1 APPPATH\Controllers\Home.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 27)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:41:31 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 29.
 1 APPPATH\Controllers\Home.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 29)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:41:33 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 29.
 1 APPPATH\Controllers\Home.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 29)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:43:44 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 30.
 1 APPPATH\Controllers\Home.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 30)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:44:45 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 31.
 1 APPPATH\Controllers\Home.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:48:14 --> Undefined variable $results
in APPPATH\Views\welcome_message.php on line 14.
 1 APPPATH\Views\welcome_message.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $results', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php', 14)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(39): view('welcome_message')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 05:48:29 --> Undefined variable $results
in APPPATH\Views\welcome_message.php on line 14.
 1 APPPATH\Views\welcome_message.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $results', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php', 14)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(39): view('welcome_message')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 06:08:41 --> Undefined variable $userModel
in APPPATH\Controllers\Home.php on line 57.
 1 APPPATH\Controllers\Home.php(57): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Home.php', 57)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->store()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 06:10:11 --> Allowed fields must be specified for model: "App\Models\Home\User"
in SYSTEMPATH\Model.php on line 736.
 1 SYSTEMPATH\Model.php(736): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Home\\User')
 2 SYSTEMPATH\BaseModel.php(763): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Home.php(57): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->store()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 06:11:34 --> Allowed fields must be specified for model: "App\Models\Home\User"
in SYSTEMPATH\Model.php on line 736.
 1 SYSTEMPATH\Model.php(736): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Home\\User')
 2 SYSTEMPATH\BaseModel.php(763): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 4 APPPATH\Controllers\Home.php(57): CodeIgniter\Model->insert([...], false)
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->store()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 06:14:40 --> Allowed fields must be specified for model: "App\Models\Home\User"
in SYSTEMPATH\Model.php on line 736.
 1 SYSTEMPATH\Model.php(736): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Home\\User')
 2 SYSTEMPATH\BaseModel.php(763): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 4 APPPATH\Controllers\Home.php(58): CodeIgniter\Model->insert([...], false)
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->store()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 06:16:45 --> Allowed fields must be specified for model: "App\Models\Home\User"
in SYSTEMPATH\Model.php on line 736.
 1 SYSTEMPATH\Model.php(736): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Home\\User')
 2 SYSTEMPATH\BaseModel.php(763): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 4 APPPATH\Controllers\Home.php(58): CodeIgniter\Model->insert([...], false)
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->store()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 06:17:57 --> Allowed fields must be specified for model: "App\Models\Home\User"
in SYSTEMPATH\Model.php on line 736.
 1 SYSTEMPATH\Model.php(736): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Home\\User')
 2 SYSTEMPATH\BaseModel.php(763): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Home.php(58): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->store()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 06:20:06 --> Allowed fields must be specified for model: "App\Models\Home\User"
in SYSTEMPATH\Model.php on line 736.
 1 SYSTEMPATH\Model.php(736): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Home\\User')
 2 SYSTEMPATH\BaseModel.php(763): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Home.php(58): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->store()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-11 06:23:21 --> Allowed fields must be specified for model: "App\Models\Home\User"
in SYSTEMPATH\Model.php on line 736.
 1 SYSTEMPATH\Model.php(736): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Home\\User')
 2 SYSTEMPATH\BaseModel.php(763): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Home.php(59): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->store()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
